---
- name: Restart cron
  service:
    name: cron
    state: restarted
  listen: "restart time reliant services"

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  listen: "restart time reliant services"
