---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Disable server tokens
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '# server_tokens off;' 
    line: '  server_tokens off;'
    backrefs: yes
  notify: 'Restart nginx'
