---
- name: Install rtorrent
  package:
    name: rtorrent
    state: present

- name: Install screen
  package:
    name: screen
    state: present

- name: Copy .rtorrent.rc config file
  template:
    src: rtorrent.rc.j2
    dest: "/home/{{ username }}/.rtorrent.rc"

- name: Create rtorrent directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - /home/{{ username }}/downloads/.session
    - /home/{{ username }}/downloads/~watch

- name: Copy rtorrent service file
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: Enable and start rtorrent service
  systemd:
    name: rtorrent
    enabled: yes
    state: started
    daemon_reload: yes

