---
- name: Set timezone to London
  timezone:
    name: Europe/London
  notify: "restart time reliant services"

- name: Generate en_GB.UTF-8 locale
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Set locale to en_GB.UTF-8 (if not already) 
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=en_GB.UTF-8'
    backrefs: yes
