---
- name: Install rutorrent dependencies
  package: 
    name: "{{ item }}"
    state: present
  with_items:
  - zip
  - unzip
  - zlib1g-dev
  - ffmpeg
  - mediainfo
  - unrar
  - rar
  - git
  - subversion

- name: Download rutorrent package
  git:
    repo: https://github.com/Novik/ruTorrent
    dest: /opt/rutorrent

- name: Replace rutorrent config
  copy:
    src: config.php
    dest: /opt/rutorrent/conf/config.php

- name: Replace rutorrent plugins config
  copy:
    src: plugins.ini
    dest: /opt/rutorrent/conf/plugins.ini

- name: Set rutorrent directory permissions
  file:
    state: directory
    dest: /opt/rutorrent
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
