---
- name: Add teamspeak user
  user:
    name: teamspeak
    system: yes
    createhome: no
    shell: /bin/false

- name: Get latest teamspeak server version
  # get_url or uri module possible here?
  shell: wget -q https://www.teamspeak.com/en/downloads.html -O - | grep -m 1 -A 2 'Server 64-bit' | grep -E -o '.\..\..{1,2}\..'
  register: teamspeakVersion

- name: Download teamspeak bz2
  get_url:
    url: http://dl.4players.de/ts/releases/{{ teamspeakVersion.stdout }}/teamspeak3-server_linux_amd64-{{ teamspeakVersion.stdout }}.tar.bz2
    dest: /tmp/ts3-{{ teamspeakVersion.stdout }}.tar.bz2

- name: Extract teamspeak bz2
  unarchive:
    src: /tmp/ts3-{{ teamspeakVersion.stdout }}.tar.bz2
    remote_src: yes
    dest: /opt/
    mode: 0700
    owner: teamspeak
    group: teamspeak
    creates: /opt/teamspeak3-server_linux_amd64

- name: Copy teamspeak systemd service file
  copy:
    src: teamspeak.service
    dest: /etc/systemd/system/teamspeak.service

- name: Enable and start teamspeak service
  systemd:
    name: teamspeak
    enabled: yes
    state: started
    daemon_reload: yes
