---
- name: Add teamspeak user
  user:
    name: teamspeak
    system: yes
    createhome: no
    shell: /bin/false

- name: Download teamspeak bz2
  get_url:
    url: http://dl.4players.de/ts/releases/3.0.13.8/teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
    dest: /tmp/ts3-3.0.13.8.tar.bz2

- name: Extract teamspeak bz2
  unarchive:
    src: /tmp/ts3-3.0.13.8.tar.bz2
    remote_src: yes
    dest: /opt/
    mode: 0700
    owner: teamspeak
    group: teamspeak
    creates: /opt/teamspeak3-server_linux_amd64

- name: Copy teamspeak systemd service file
  copy:
    src: teamspeak.service
    dest: /etc/systemd/system/teamspeak.service

- name: Enable and start teamspeak service
  systemd:
    name: teamspeak
    enabled: yes
    state: started
    daemon_reload: yes
