---
- name: Install rtorrent
  include_role:
    name: rtorrent

- name: Download rutorrent
  include_role:
    name: rutorrent

- name: Install nginx
  include_role:
    name: nginx

- name: Install xml-rpc
  package: 
    name: libxmlrpc-c++8v5
    state: present

- name: Install PHP 7.0
  package:
    name: php7.0
    state: present


