---
- name: Install rtorrent
  include_role:
    name: rtorrent

- name: Download rutorrent
  include_role:
    name: rutorrent

- name: Install nginx
  include_role:
    name: nginx

- name: Install apache2-utils
  package:
    name: apache2-utils
    state: present

- name: Install passlib for htpasswd
  package:
    name: python-passlib
    state: present

- name: Create rutorrent htpasswd
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ username }}"
    password: "{{ password }}"
    owner: root
    group: root
    mode: 0640

- name: Create rutorrent http symlink
  file:
    src: /opt/rutorrent
    dest: /var/www/html/rutorrent
    owner: rtorrent
    group: rtorrent
    state: link

- name: Copy default site conf to available
  copy:
    src: default
    dest: /etc/nginx/sites-available/default

- name: Copy rutorrent site conf to available
  copy:
    src: rutorrent
    dest: /etc/nginx/sites-available/rutorrent

- name: Symlink rutorrent site conf to enabled
  file:
    src: /etc/nginx/sites-available/rutorrent
    dest: /etc/nginx/sites-enabled/rutorrent
    owner: root
    group: root
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart PHP 7.3 FPM
  service: 
    name: php7.3-fpm
    state: restarted
