---
- name: Copy bashrc
  copy:
    src: files/bashrc
    dest: ~/.bashrc
    backup: yes

- name: Copy screenrc
  copy:
    src: files/screenrc
    dest: ~/.screenrc
    backup: yes

- name: Install bash auto complete
  package:
    name: bash-completion
    state: present
