---
- name: Install vim
  apt:
    name: vim
    state: latest

- name: Copy vimrc config
  copy:
    src: files/vimrc
    dest: /etc/vim/vimrc
    force: no

- name : Install rsync locally
  apt:
    name: rsync
    state: latest
  delegate_to: localhost

- name: Copy .vim folder
  synchronize:
    src: files/vim/
    dest: ~/.vim/
