---
- name: Install vim
  package:
    name: vim
    state: latest

- name: Copy vimrc config
  copy:
    src: vimrc
    dest: /etc/vim/vimrc

- name: Install rsync locally
  package:
    name: rsync
    state: present
  delegate_to: localhost

- name: Copy .vim folder
  synchronize:
    src: files/vim/
    dest: "{{ ansible_env.HOME }}/.vim/"
    perms: no
  

- name: Set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
